### ISSUE TITLE
java.util.IllegalFormatConversionException in JSONParserException.internalGetMessage

### ISSUE THREAD

**Issue by andreasvef** [billdavidson/JSONUtil#4]
The order of arguments to format() does not match the order in the resource bundle for "unrecognizedData".

Exception in thread "main" java.util.IllegalFormatConversionException: d != java.lang.String
    at java.util.Formatter$FormatSpecifier.failConversion(Unknown Source)
    at java.util.Formatter$FormatSpecifier.printInteger(Unknown Source)
    at java.util.Formatter$FormatSpecifier.print(Unknown Source)
    at java.util.Formatter.format(Unknown Source)
    at java.util.Formatter.format(Unknown Source)
    at java.lang.String.format(Unknown Source)
    at org.kopitubruk.util.json.JSONParserException.internalGetMessage(JSONParserException.java:133)
    at org.kopitubruk.util.json.JSONException.getLocalizedMessage(JSONException.java:80)

**Comment by billdavidson** [comment]
This has been fixed in the trunk branch and the fix will be in the next release.

**Comment by billdavidson** [comment]
This fix has been merged into the java7, java6 and java5 branches.

**Comment by billdavidson** [comment]
@andreasvef : If you would like to test the fix, you can download it here:

https://github.com/billdavidson/billdavidson.github.io/blob/master/JSONUtil/JSONUtil-1.8-java7-SNAPSHOT.jar

**Comment by andreasvef** [comment]
Thank you very much, now it works as expected

**Comment by billdavidson** [comment]
Fixed in release 1.8
